### ISSUE TITLE
Fix flake8 update in `.pre-commit-config.yaml` across repositories

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/repo-template#74]
# Problem

Some repositories use the GitLab flake8 mirror URL in `.pre-commit-config.yaml`. The current canonical URL is `https://github.com/PyCQA/flake8` [^1]

This in itself is not a problem.

Except that, for reasons I cannot discern (maybe difference in branch tagging?), running `pre-commit autoupdate` with the GitLab URL does not update flake8 to 4.0.1. It quite happily claims an earlier version as being the latest (witnessed with `3.9.2`).

Updating the URL, then running `pre-commit autoupdate` then correctly finds the latest version.

It seems sensible to use the canonical URL, in any case, in case the mirror gets deleted.

# Repositories affected

Found via GitHub's [code search preview](https://cs.github.com), which does a better job of giving you a direct list of matching repositories

- [x] osgithub; opensafely-core/osgithub#64
- [x] osrelease; opensafely-core/osrelease#58
- [x] actions-registry‎; opensafely-core/actions-registry#125
- [x] release-hatch‎; opensafely-core/release-hatch#118
- [x] mkdocs-opensafely-databuilder‎; opensafely-core/mkdocs-opensafely-databuilder#37
- [x] opencodelists‎; opensafely-core/opencodelists#1330
- [x] databuilder‎; opensafely-core/databuilder#648
- [x] job-server; opensafely-core/job-server#1960
- [x] hq‎ (won't fix; archived)
- [x] cohort-extractor-v2-documentation‎ (won't fix; archived)

# Fix

1. Update the URL.
2. (Optionally) Merge any outstanding flake8 update PRs.
3. Update `.pre-commit-config.yaml` if it is out of sync with the current specified Python requirements (as in any `requirements*.txt` files).

[^1]: We're currently using an all lowercase URL in this template, but that's OK as GitHub treats it the same.

**Comment by StevenMaude** [comment]
This just needs the open PRs merging to be done.
