### ISSUE TITLE
Fix isort update URL in `.pre-commit-config.yaml` across repositories

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/repo-template#76]
`https://github.com/pre-commit/mirrors-isort` is used in various places and is now an archived repository.

The correct canonical URL is as in this template: `https://github.com/PyCQA/isort`

# Repositories affected

- [x] osrelease‎; opensafely-core/osrelease#58
- [x] release-hatch‎; opensafely-core/release-hatch#118
- [x] opencodelists‎; opensafely-core/opencodelists#1330
- [x] hq‎ (won't fix; archived)
- [x] cohort-extractor-v2-documentation‎ (won't fix; archived)

**Comment by StevenMaude** [comment]
This just needs the open PRs merging to be done.
